progress:
  '#changed': 1522198935
  '#changed_by': '0'
  '#items':
    thunder_post_update_install_config_selector:
      '#completed': 1522198935
      '#uid': '0'
    thunder_article_update_8102:
      '#completed': 1522198935
      '#uid': '0'
    thunder__thunder_update_8119:
      '#completed': 1522198935
      '#uid': '0'
    thunder__thunder_update_8117:
      '#completed': 1522198935
      '#uid': '0'
    thunder__thunder_update_8118:
      '#completed': 1522198935
      '#uid': '0'
    thunder_media_update_8108:
      '#completed': 1522198935
      '#uid': '0'
    thunder__thunder_update_8116:
      '#completed': 1522198935
      '#uid': '0'
    thunder__thunder_update_8115:
      '#completed': 1522198935
      '#uid': '0'
    thunder_media_update_8106:
      '#completed': 1522198935
      '#uid': '0'
    thunder_taxonomy_update_8002:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__media_entity_pinterest:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__content_lock:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__empty_fields:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__thunder_admin_ux:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__media_paragraph:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__responsive_preview:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__access_unpublished:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__shariff:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__remove_entity_browser_language_filter:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__metatag_facebook:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__config_update:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__image_video_paragraph:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__instagram_edit_preview:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__diff:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__thunder_riddle:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__paragraphs_modal:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__thunder_liveblog:
      '#completed': 1522198935
      '#uid': '0'
    v1_1__thunder_amp:
      '#completed': 1522198935
      '#uid': '0'
  '#completed_items': 28
